### ISSUE TITLE
Importing bumped file creates an infinite loop

### ISSUE THREAD

**Issue by Spensaur-K** [johnagan/bump-webpack-plugin#2]
I've configured the library to bump my package.json file, but since I import package.json into my bundle, it creates an infinite loop when bundling and keeps patching forever

**Comment by johnagan** [comment]
I'm not sure I follow, but you're welcome to open a PR to attempt a fix.

**Comment by Spensaur-K** [comment]
Sorry, I'm running webpack in watch mode. When the plugin bumps the version, webpack counts the bump as a file change and the plugin recompiles my bundle which causes the plugin to bump the version again.
I did some digging and tried changing `compiler.plugin('done')` to `compiler.plugin('compilation')` but that didn't work. I don't see how it could be fixed yet
